//! Renders `[wm]` into GlazeWM's own config format.
//!
//! The shape here is not guessed: it is the schema verified to start
//! GlazeWM 3.10.1 successfully on Windows 10. GlazeWM is a GUI-subsystem
//! binary, so a bad config produces no console output at all and it simply
//! dies -- the errors go to `~/.glzr/glazewm/errors.log`.

use crate::config::Config;
use serde::Serialize;
use std::path::PathBuf;

#[derive(Serialize)]
struct GlazeConfig {
    general: General,
    gaps: Gaps,
    window_effects: WindowEffects,
    window_behavior: WindowBehavior,
    workspaces: Vec<Workspace>,
    keybindings: Vec<Keybinding>,
}

#[derive(Serialize)]
struct General {
    startup_commands: Vec<String>,
    shutdown_commands: Vec<String>,
    config_reload_commands: Vec<String>,
    focus_follows_cursor: bool,
    toggle_workspace_on_refocus: bool,
    hide_method: String,
    show_all_in_taskbar: bool,
}

#[derive(Serialize)]
struct Gaps {
    scale_with_dpi: bool,
    inner_gap: String,
    outer_gap: OuterGap,
}

#[derive(Serialize)]
struct OuterGap {
    top: String,
    right: String,
    bottom: String,
    left: String,
}

#[derive(Serialize)]
struct WindowEffects {
    focused_window: EffectGroup,
    other_windows: EffectGroup,
}

#[derive(Serialize)]
struct EffectGroup {
    border: Border,
}

#[derive(Serialize)]
struct Border {
    enabled: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    color: Option<String>,
}

#[derive(Serialize)]
struct WindowBehavior {
    initial_state: String,
    state_defaults: StateDefaults,
}

#[derive(Serialize)]
struct StateDefaults {
    floating: FloatingDefaults,
    fullscreen: FullscreenDefaults,
}

#[derive(Serialize)]
struct FloatingDefaults {
    centered: bool,
    shown_on_top: bool,
}

#[derive(Serialize)]
struct FullscreenDefaults {
    maximized: bool,
    shown_on_top: bool,
}

#[derive(Serialize)]
struct Workspace {
    name: String,
}

#[derive(Serialize)]
struct Keybinding {
    commands: Vec<String>,
    bindings: Vec<String>,
}

pub fn config_path() -> PathBuf {
    let home = std::env::var("USERPROFILE").unwrap_or_default();
    PathBuf::from(home).join(".glzr").join("glazewm").join("config.yaml")
}

/// Turn Baton's `[wm]` section into a complete GlazeWM config document.
pub fn render(cfg: &Config) -> anyhow::Result<String> {
    let wm = &cfg.wm;

    let doc = GlazeConfig {
        general: General {
            startup_commands: Vec::new(),
            shutdown_commands: Vec::new(),
            config_reload_commands: Vec::new(),
            focus_follows_cursor: wm.focus_follows_cursor,
            toggle_workspace_on_refocus: false,
            // Cloaking beats SW_HIDE: a cloaked window keeps its state and
            // cannot be stranded invisible the way a hidden one can.
            hide_method: "cloak".into(),
            show_all_in_taskbar: false,
        },
        gaps: Gaps {
            scale_with_dpi: true,
            inner_gap: format!("{}px", wm.gaps.inner),
            outer_gap: OuterGap {
                top: format!("{}px", wm.gaps.outer),
                right: format!("{}px", wm.gaps.outer),
                bottom: format!("{}px", wm.gaps.outer),
                left: format!("{}px", wm.gaps.outer),
            },
        },
        window_effects: WindowEffects {
            focused_window: EffectGroup {
                border: Border {
                    enabled: wm.focused_border.is_some(),
                    color: wm.focused_border.clone(),
                },
            },
            other_windows: EffectGroup {
                border: Border { enabled: false, color: None },
            },
        },
        window_behavior: WindowBehavior {
            initial_state: "tiling".into(),
            state_defaults: StateDefaults {
                floating: FloatingDefaults { centered: true, shown_on_top: false },
                fullscreen: FullscreenDefaults { maximized: false, shown_on_top: false },
            },
        },
        workspaces: wm
            .workspaces
            .iter()
            .map(|name| Workspace { name: name.clone() })
            .collect(),
        keybindings: wm
            .keys
            .iter()
            .map(|(binding, command)| Keybinding {
                commands: vec![command.clone()],
                bindings: vec![binding.clone()],
            })
            .collect(),
    };

    let body = serde_yaml::to_string(&doc)?;
    Ok(format!(
        "# Generated by baton. Do not edit; edit baton.toml and run `baton apply`.\n\
         # Your previous file was saved and can be restored with `baton rollback`.\n\
         {body}"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(text: &str) -> Config {
        Config::parse(text).unwrap()
    }

    #[test]
    fn renders_a_document_with_every_section_glazewm_requires() {
        let out = render(&parse("")).unwrap();
        for section in [
            "general:",
            "gaps:",
            "window_effects:",
            "window_behavior:",
            "workspaces:",
            "keybindings:",
        ] {
            assert!(out.contains(section), "missing {section} in:\n{out}");
        }
    }

    #[test]
    fn gaps_are_emitted_in_the_px_form_glazewm_expects() {
        let out = render(&parse("[wm.gaps]\ninner = 14\nouter = 7")).unwrap();
        assert!(out.contains("inner_gap: 14px"), "{out}");
        assert!(out.contains("top: 7px"), "{out}");
    }

    #[test]
    fn resolved_palette_colour_reaches_the_border() {
        let cfg = parse(
            r##"
            [palette]
            accent = "#8aadf4"
            [wm]
            focused_border = "@palette.accent"
            "##,
        );
        let out = render(&cfg).unwrap();
        assert!(out.contains("#8aadf4"), "{out}");
        assert!(out.contains("enabled: true"), "{out}");
        // No unresolved reference may ever reach a downstream tool.
        assert!(!out.contains("@palette"), "{out}");
    }

    #[test]
    fn no_border_colour_means_the_border_is_disabled() {
        let out = render(&parse("")).unwrap();
        assert!(out.contains("enabled: false"), "{out}");
        assert!(!out.contains("color:"), "absent colour must be omitted:\n{out}");
    }

    #[test]
    fn keybinds_become_one_binding_entry_each() {
        let cfg = parse(
            r##"
            [wm.keys]
            "alt+j" = "focus --direction down"
            "alt+k" = "focus --direction up"
            "##,
        );
        let out = render(&cfg).unwrap();
        assert_eq!(out.matches("- commands:").count(), 2, "{out}");
        assert!(out.contains("alt+j"), "{out}");
        assert!(out.contains("focus --direction down"), "{out}");
    }

    #[test]
    fn workspaces_are_rendered_in_order() {
        let cfg = parse(r#"[wm]
workspaces = ["web", "code", "chat"]"#);
        let out = render(&cfg).unwrap();
        let web = out.find("web").unwrap();
        let code = out.find("code").unwrap();
        let chat = out.find("chat").unwrap();
        assert!(web < code && code < chat, "{out}");
    }

    #[test]
    fn output_is_valid_yaml_that_round_trips() {
        let out = render(&parse("")).unwrap();
        let parsed: serde_yaml::Value =
            serde_yaml::from_str(&out).expect("rendered config must be valid YAML");
        assert!(parsed.get("general").is_some());
    }

    #[test]
    fn the_generated_file_warns_against_hand_editing() {
        let out = render(&parse("")).unwrap();
        assert!(out.starts_with("# Generated by baton"));
        assert!(out.contains("baton rollback"));
    }
}
