//! Renders `[bar]` into Zebar's settings, and exports the palette as CSS.
//!
//! Zebar 3.x gets its widgets from marketplace packs, so the surface a config
//! tool can honestly own is which widgets launch, not what they look like:
//! pack internals live in marketplace-managed directories and rewriting them
//! would be undone by the next pack update.
//!
//! So Baton does two things. It owns `settings.json`, which is a documented,
//! schema'd file. And it writes the palette out as CSS custom properties that
//! *your own* widget pack can `@import`, which is the honest way to get one
//! palette across the whole desktop without fighting the marketplace.

use crate::config::Config;
use anyhow::Result;
use serde::Serialize;
use std::path::PathBuf;

/// Matches the schema Zebar 3.3.1 writes on first run.
#[derive(Serialize)]
struct Settings {
    #[serde(rename = "$schema")]
    schema: String,
    #[serde(rename = "startupConfigs")]
    startup_configs: Vec<StartupConfig>,
}

#[derive(Serialize)]
struct StartupConfig {
    pack: String,
    widget: String,
    preset: String,
}

const SCHEMA: &str =
    "https://github.com/glzr-io/zebar/raw/v3.3.1/resources/settings-schema.json";

fn dir() -> PathBuf {
    let home = std::env::var("USERPROFILE").unwrap_or_default();
    PathBuf::from(home).join(".glzr").join("zebar")
}

pub fn settings_path() -> PathBuf {
    dir().join("settings.json")
}

/// A stylesheet of the palette, for a widget pack to import. Named distinctly
/// so it can never collide with a file a pack owns.
pub fn palette_css_path() -> PathBuf {
    dir().join("baton-palette.css")
}

pub fn render_settings(cfg: &Config) -> Result<String> {
    let doc = Settings {
        schema: SCHEMA.to_string(),
        startup_configs: cfg
            .bar
            .widgets
            .iter()
            .map(|w| StartupConfig {
                pack: w.pack.clone(),
                widget: w.widget.clone(),
                preset: w.preset.clone(),
            })
            .collect(),
    };
    // Zebar wrote its own file pretty-printed; match that so a hand-diff of
    // the file is readable.
    Ok(format!("{}\n", serde_json::to_string_pretty(&doc)?))
}

/// The palette as CSS custom properties on `:root`.
pub fn render_palette_css(cfg: &Config) -> String {
    let mut out = String::from(
        "/* Generated by baton from the [palette] in baton.toml.\n   \
         Import this from your widget pack:  @import '../../baton-palette.css';\n   \
         Do not edit; edit baton.toml and run `baton apply`. */\n:root {\n",
    );
    for (name, colour) in &cfg.palette {
        // TOML keys can contain characters that are not valid in a CSS ident.
        out.push_str(&format!("  --{}: {};\n", css_ident(name), colour));
    }
    out.push_str("}\n");
    out
}

/// Make a palette name safe to use as a CSS custom property.
fn css_ident(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
            out.push(ch);
        } else {
            out.push('-');
        }
    }
    // A custom property must not start with a digit.
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '-');
    }
    out
}

fn exe_path() -> PathBuf {
    let candidates = [
        std::env::var("ProgramFiles").map(|p| PathBuf::from(p).join(r"glzr.io\Zebar\zebar.exe")),
        std::env::var("LOCALAPPDATA")
            .map(|p| PathBuf::from(p).join(r"Programs\zebar\zebar.exe")),
    ];
    for candidate in candidates.into_iter().flatten() {
        if candidate.exists() {
            return candidate;
        }
    }
    PathBuf::from("zebar")
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Restart {
    /// Zebar was running and has been restarted onto the new settings.
    Done,
    /// Zebar was not running, so the new settings apply when you start it.
    NotRunning,
    Unavailable(&'static str),
}

pub fn is_running() -> bool {
    // Zebar has no "is it up" query that does not need it up, so ask the OS.
    std::process::Command::new("tasklist")
        .args(["/FI", "IMAGENAME eq zebar.exe", "/NH"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).to_lowercase().contains("zebar.exe"))
        .unwrap_or(false)
}

/// `startupConfigs` is only read at launch, so new settings need a restart
/// rather than a reload.
pub fn restart() -> Restart {
    if !is_running() {
        return Restart::NotRunning;
    }
    let killed = std::process::Command::new("taskkill")
        .args(["/IM", "zebar.exe", "/F"])
        .output()
        .is_ok();
    if !killed {
        return Restart::Unavailable("could not stop the running Zebar");
    }
    std::thread::sleep(std::time::Duration::from_millis(600));

    // Detach, and discard its stdio. Left attached, Zebar inherits our console
    // and spews its provider logs over baton's output, and closing the terminal
    // would take the bar down with it.
    use std::os::windows::process::CommandExt;
    const DETACHED_PROCESS: u32 = 0x0000_0008;
    const CREATE_NEW_PROCESS_GROUP: u32 = 0x0000_0200;

    match std::process::Command::new(exe_path())
        .arg("startup")
        .creation_flags(DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .stdin(std::process::Stdio::null())
        .spawn()
    {
        Ok(_) => Restart::Done,
        Err(_) => Restart::Unavailable("could not start Zebar again"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(text: &str) -> Config {
        Config::parse(text).unwrap()
    }

    #[test]
    fn settings_match_the_shape_zebar_writes_itself() {
        let cfg = parse(
            r#"[bar]
backend = "zebar"

[[bar.widgets]]
pack = "glzr-io.starter"
widget = "vanilla"
preset = "default""#,
        );
        let out = render_settings(&cfg).unwrap();
        let doc: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(doc["$schema"], SCHEMA);
        assert_eq!(doc["startupConfigs"][0]["pack"], "glzr-io.starter");
        assert_eq!(doc["startupConfigs"][0]["widget"], "vanilla");
        assert_eq!(doc["startupConfigs"][0]["preset"], "default");
    }

    #[test]
    fn preset_defaults_so_the_common_case_is_two_lines() {
        let cfg = parse(
            r#"[bar]
backend = "zebar"

[[bar.widgets]]
pack = "glzr-io.starter"
widget = "vanilla""#,
        );
        let out = render_settings(&cfg).unwrap();
        assert!(out.contains("\"preset\": \"default\""), "{out}");
    }

    #[test]
    fn several_widgets_keep_their_order() {
        let cfg = parse(
            r#"[bar]
backend = "zebar"

[[bar.widgets]]
pack = "a"
widget = "first"

[[bar.widgets]]
pack = "b"
widget = "second""#,
        );
        let out = render_settings(&cfg).unwrap();
        assert!(out.find("first").unwrap() < out.find("second").unwrap(), "{out}");
    }

    #[test]
    fn palette_becomes_css_custom_properties() {
        let cfg = parse(
            r##"[palette]
accent = "#8aadf4"
bg = "#24273a""##,
        );
        let css = render_palette_css(&cfg);
        assert!(css.contains("--accent: #8aadf4;"), "{css}");
        assert!(css.contains("--bg: #24273a;"), "{css}");
        assert!(css.contains(":root {"), "{css}");
    }

    #[test]
    fn palette_names_are_made_safe_for_css() {
        // A TOML key can hold things a CSS ident cannot.
        assert_eq!(css_ident("accent"), "accent");
        assert_eq!(css_ident("accent.bright"), "accent-bright");
        assert_eq!(css_ident("my colour"), "my-colour");
        assert_eq!(css_ident("2cool"), "-2cool");
    }

    #[test]
    fn an_empty_palette_still_produces_valid_css() {
        let css = render_palette_css(&parse(""));
        assert!(css.contains(":root {"));
        assert!(css.trim_end().ends_with('}'));
    }

    #[test]
    fn no_widgets_means_an_empty_startup_list_not_a_broken_file() {
        let out = render_settings(&parse("")).unwrap();
        let doc: serde_json::Value = serde_json::from_str(&out).unwrap();
        assert_eq!(doc["startupConfigs"].as_array().unwrap().len(), 0);
    }
}
